name: Build for Linux

on: workflow_dispatch

jobs:
  build-linux:
    environment: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [
          redhat,
          ubuntu
        ]

    steps:
      - name: Checkout arelle
        uses: actions/checkout@v3.0.2
      - name: Checkout EdgarRenderer
        uses: actions/checkout@v3.0.2
        with:
          repository: Arelle/EdgarRenderer
          path: arelle/plugin/EdgarRenderer
      - name: Cleanup EdgarRenderer
        run: rm -rf arelle/plugin/EdgarRenderer/.git
      - name: Checkout XULE
        uses: actions/checkout@v3.0.2
        with:
          repository: xbrlus/xule
          path: xule
      - name: Move XULE plugins
        run: |
          mv xule/plugin/validate/* arelle/plugin/validate/
          rm -rf xule/plugin/validate
          mv xule/plugin/* arelle/plugin/
      - name: Cleanup XULE
        run: rm -rf xule
      - name: Checkout ixbrl-viewer
        uses: actions/checkout@v3.0.2
        with:
          repository: Workiva/ixbrl-viewer
          path: ixbrl-viewer
      - name: Set up Node JS
        uses: actions/setup-node@v3.4.1
        with:
          node-version: lts/*
      - name: Build ixbrl-viewer
        working-directory: ixbrl-viewer
        run: |
          npm install
          make prod
      - name: Move ixbrl-viewer plugin
        run: mv ixbrl-viewer/iXBRLViewerPlugin arelle/plugin/
      - name: Cleanup ixbrl-viewer
        run: rm -rf ixbrl-viewer
      - name: Docker registry login
        uses: docker/login-action@v2.0.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME }}
          password: ${{ secrets.REDHAT_PASSWORD }}
      - name: Docker setup buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Docker build
        uses: docker/build-push-action@v3.1.1
        with:
          build-args: |
            "PYTHON_VERSION=3.9.13"
            "TCLTK_VERSION=8.6.12"
          context: .
          file: docker/${{ matrix.distro }}.Dockerfile
          load: true
          secrets: |
            "redhat_username=${{ secrets.REDHAT_USERNAME }}"
            "redhat_password=${{ secrets.REDHAT_PASSWORD }}"
          tags: arelle:arelle
      - name: Docker copy build artifact
        run: |
          docker create --name arelle arelle:arelle
          docker cp arelle:/build/dist/ dist/
          docker rm -v arelle
      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ matrix.distro }} distribution
          path: dist/*.tgz
