name: Run Python Unit Tests
on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Install Python 3
        uses: actions/setup-python@v4.2.0
        with:
          cache: 'pip' # caching pip dependencies
          check-latest: true
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
